export enum SocketEvents {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  UPDATE_ROOM = 'UPDATE_ROOM',
  RECEIVE_CHAT = 'RECEIVE_CHAT',
  SEND_CHAT = 'SEND_CHAT',
  SET_LOBBY_ROOMS = 'SET_LOBBY_ROOMS',
  SET_LOBBY_ROOM = 'SET_LOBBY_ROOM',
  DELETE_LOBBY_ROOM = 'DELETE_LOBBY_ROOM',
}
