import { toast } from 'react-toastify';

export const SOCKET_URI = process.env.NEXT_PUBLIC_SOCKET_URI;
export const BACKEND_URL = process.env.NEXT_PUBLIC_SOCKET_URI;
export const HEADERS = { 'Content-Type': 'application/json' };
export const TOAST_OPTION = { autoClose: 3000, position: toast.POSITION.BOTTOM_RIGHT };
export const SUCCESS = 'SUCCESS';
export const FAILED = 'FAILED';
export const LOGIN_SUCC_MSG = '로그인에 성공했습니다.';
export const COPY_EMPTY_MSG = '초대 코드를 입력해 주세요.';
export const COPY_SUCC_MSG = '초대코드가 복사되었습니다.';
export const COPY_ERR_MSG = '존재하지 않는 초대코드입니다.';
export const ID_EMPTY_MSG = '아이디를 입력해 주세요';
export const PASSWORD_EMPTY_MSG = '비밀번호를 입력해 주세요.';
export const PASSWORD_ERR_MSG = '비밀번호가 다릅니다.';
export const NICKNAME_EMPTY_MSG = '닉네임을 입력해 주세요.';
export const PLAYLIST_EMPTY_MSG = '플레이리스트가 존재하지 않습니다.';
export const PLAYLIST_ERR_MSG = '플레이리스트 등록에 실패하였습니다.';
export const PLAYLIST_INPUT_ERR_MSG = '플레이리스트 입력을 확인해 주세요..';
export const PLAYLIST_DELETE_ERR_MSG = '플레이리스트 삭제에 실패하였습니다.';
export const GAME_ENTER_ERR_MSG = '이미 해당 방에 참여중입니다.';
