name: CI/CD to NCloud

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-18.04

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            node -v || {apt update && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt install nodejs} &&
            npm i -g npm
            npm i -g pm2
            npm i -g yarn
            whoami | xargs echo 'USERNAME:' &&
            echo 'SHELL:' ${0} &&
            node -v | xargs echo 'NODE VERSION:' &&
            whereis pm2
            whereis yarn
            npm i -g pm2
            npm i -g yarn
            cd web02-booducksound
            git pull origin main
            pm2 kill
            cd backend
            yarn install
            yarn run build
            yarn run deploy
            cd ../frontend
            yarn install
            yarn run build
            yarn run deploy
