name: CI/CD to NCloud

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            bash
            cd ~/web02-booducksound
            git pull origin main
            pm2 kill
            cd backend
            yarn install
            yarn run build
            yarn run deploy
            cd ../frontend
            yarn install
            yarn run build
            yarn run deploy
